name: Checks

on:
  pull_request:

env:
  PYTHON_VERSION_DEFAULT: "3.10.8"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.8
      - name: Install the latest version of rye
        run: make dev
      - name: Run checks
      - uses: pre-commit/action@v3.0.1
