name: template-release

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: release environment
        required: true
      url:
        type: string
        description: release url
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - uses: astral-sh/setup-uv@v5
      - name: Install project
        run: uv sync --all-extras
      - name: Build package
        run: make build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  release:
    needs: build
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to  ${{ vars.PYPI_NAME }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ vars.PYPI_URL }}
          packages-dir: dist/
          verbose: true
