name: dev-release
on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+-dev*']
  workflow_dispatch:

concurrency:
  group: test
  cancel-in-progress: true

jobs:
  dev-release:
    name: dev-release
    uses: ./.github/workflows/_release.yaml
    with:
      environment: DEV
      url: https://test.pypi.org/p/gentroutils
