name: dev-release
on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+-*']
  workflow_dispatch:

concurrency:
  group: test
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: pyproject.toml
      - uses: astral-sh/setup-uv@v5
        with:
          python-version:  pyproject.toml
      - name: Install project
        run: uv sync --all-extras
      - name: Build package
        run: make build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  test-release:
    needs: build
    runs-on: ubuntu-latest
    environment: TEST
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/
