name: Checks

on:
  pull_request:
    branches:
      - dev

jobs:
  check:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        include:
          - command: "test"
          - command: "type-check"
          # - command: "dep-check"
          #   python-version: "3.10"
          # - command: "lint"
          #   python-version: "3.10"
    name: ${{ matrix.command }}-${{ matrix.python-version }}
    # concurrency:
    #   group: ${{ matrix.python-version }}-${{ github.workflow }}-${{ github.ref }}
    #   cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version:  ${{ matrix.python-version }}
      - name: Install project
        run: uv sync --all-extras
      - name: Run test
        run: make ${{ matrix.command }}

  # types:
  #   strategy:
  #     matrix:
  #       python-version: ["3.10", "3.11", "3.12", "3.13"]
  #   concurrency:
  #     group: ${{ matrix.python-version }}-${{ github.workflow }}-${{ github.ref }}
  #     cancel-in-progress: true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v5
  #       with:
  #         enable-cache: true
  #         cache-dependency-glob: "uv.lock"
  #         python-version:  ${{ matrix.python-version }}
  #     - name: Install project
  #       run: uv sync --all-extras
  #     - name: Run test
  #       run: make type-check


  # lint:
  #   strategy:
  #     matrix:
  #       python-version: ["3.10"]
  #   concurrency:
  #     group: ${{ matrix.python-version }}-${{ github.workflow }}-${{ github.ref }}
  #     cancel-in-progress: true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v5
  #       with:
  #         enable-cache: true
  #         cache-dependency-glob: "uv.lock"
  #         python-version:  ${{ matrix.python-version }}
  #     - name: Install project
  #       run: uv sync --all-extras
  #     - name: Run test
  #       run: make lint


  # dependencies:
  #   strategy:
  #     matrix:
  #       python-version: ["3.10"]
  #   concurrency:
  #     group: ${{ matrix.python-version }}-${{ github.workflow }}-${{ github.ref }}
  #     cancel-in-progress: true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v5
  #       with:
  #         enable-cache: true
  #         cache-dependency-glob: "uv.lock"
  #         python-version:  ${{ matrix.python-version }}
  #     - name: Install project
  #       run: uv sync --all-extras
  #     - name: Run test
  #       run: make dep-check
