name: release
on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]']
  workflow_dispatch:

concurrency:
  group: prod
  cancel-in-progress: true

jobs:
  dev-release:
    name: dev-release
    uses: ./.github/workflows/_release.yaml
    with:
      environment: PyPI
      url: https://pypi.org/p/gentroutils
