name: Release

on:
  push:
    tags:
      - "v*"

env:
  PYTHON_VERSION_DEFAULT: "3.10.8"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: PyPI
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.8
      - name: Install uv
        uses: yezz123/setup-uv@v4
      - name: Install rye
        uses: eifinger/setup-rye@v4
        with:
          version: "latest"
      - name: Sync dependencies
        run: rye sync
      - name: Build package
        run: make build
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/gentroutils/
          packages-dir: dist/
