name: release
on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]']
  workflow_dispatch:

concurrency:
  group: prod
  cancel-in-progress: true

jobs:
  release:
    name: test-pypi-release
    uses: ./.github/workflows/_release.yaml
    with:
      environment: DEV
      url: https://test.pypi.org/p/gentroutils

  dev-release:
    needs: release
    name: pypi-release
    uses: ./.github/workflows/_release.yaml
    with:
      environment: PyPI
      url: https://pypi.org/p/gentroutils
