name: Tag

"on":
  push:
    # main branch - release, dev branch - dev release
    branches: ["main", "dev"]

concurrency:
  group: deploy
  cancel-in-progress: false

env:
  PYTHON_VERSION_DEFAULT: "3.10.8"


jobs:
